name: Update submodule

on:
  push:
    branches:
      - master

jobs:

  update-submodule-job:
    name: update submodule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEST_PAT }}
          submodules: true
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true
      - name: Commit changes
          uses: EndBug/add-and-commit@v5
          with:
            author_name: autocommit
            author_email: mail@example.com
            message: "Autocommit for submodule update"
          env:
            GITHUB_TOKEN: ${{ secrets.TEST_PAT }}

