name: Update submodule

on:
  repository_dispatch:
    types: [my-event]

jobs:

  update-submodule-job:
    name: update submodule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TEST_PAT }}
          submodules: true
      - run: |
          git config user.name "Submodule Update Workflow"
          git commit -m "Commit from GitHub Actions Submodule Update Workflow"
          git push
